[mypy]
python_version = 3.12
strict = true
warn_unreachable = true
show_error_codes = true
pretty = true
mypy_path = src

[mypy-yaml.*]
ignore_missing_imports = true

[mypy-rasterio.*]
ignore_missing_imports = true

[mypy-dask.*]
ignore_missing_imports = true

[mypy-scipy.*]
ignore_missing_imports = true

[mypy-sklearn.*]
ignore_missing_imports = true

[mypy-reportlab.*]
ignore_missing_imports = true

[mypy-geopandas.*]
ignore_missing_imports = true

[mypy-shapely.*]
ignore_missing_imports = true

[mypy-planetary_computer.*]
ignore_missing_imports = true
